# Generated by Django 3.0.8 on 2020-07-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=60)),
                ('cilindros', models.CharField(max_length=60)),
                ('potencia', models.CharField(max_length=60)),
                ('sistema_alimentacion', models.CharField(max_length=60)),
                ('suspension_delantera', models.CharField(max_length=60)),
                ('suspension_posterior', models.CharField(max_length=60)),
                ('torque', models.CharField(max_length=60)),
                ('transmision', models.CharField(max_length=60)),
                ('frenos_delanteros', models.CharField(max_length=60)),
                ('frenos_traseros', models.CharField(max_length=60)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auto', models.CharField(max_length=60)),
                ('anno', models.IntegerField()),
                ('precio', models.FloatField()),
                ('foto', models.ImageField(upload_to='')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.Modelo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.Tipo')),
            ],
        ),
    ]
